### PR TITLE
fix: Autosuggest warning for undefined enteredTextLabel when using built-in i18n

### LINKED ISSUE #1926: [Bug]: Autosuggest shouldn't warn for undefined enteredTextLabel when using built-in i18n
### Browser

Chrome, Firefox

### Package version

v3.0.0

### React version

v18.18.2

### Description

Console warning: `[Autosuggest] A value for enteredTextLabel must be provided.` in dev mode despite using the built-in i18n feature. This creates the false impression that it should be set at the component.

References:
* https://github.com/cloudscape-design/components/blob/e2bc55cf3dc218e597beb5879bf4e408f8357d6d/src/autosuggest/internal.tsx#L89-L91
* https://github.com/cloudscape-design/component-toolkit/blob/main/src/internal/logging.ts#L8-L16

### Source code

_No response_

### Reproduction

* https://codesandbox.io/p/devbox/3nc4tg?embed=1&file=%2Fsrc%2FApp.jsx
* Open dev tools and the warning will pop up
  image

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tlindsay42**
### Description

Augments the existing AutoSuggest `enteredTextLabel` check to also check whether the built-in i18n provider is in use so that it no longer provides false positive warnings when using the provider.

Ran into this issue and thought I'd fix it to prevent it from confusing others.

Related links, issue #, if available: n/a

* Fixes #1926

### How has this been tested?

Added two new unit tests for ensuring desired behaviors:
1. The existing warning is ***still*** triggered when `enteredTextLabel` is undefined and the i18n provider is not in use.
2. No warnings are triggered when `enteredTextLabel` is undefined and the i18n provider is in use.

```sh
npx jest -c jest.unit.config.js src/autosuggest/__tests__/i18n.test.tsx
```

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/autosuggest/internal.tsx [hunk 1]
```diff
@@ -86,7 +86,8 @@ const InternalAutosuggest = React.forwardRef((props: InternalAutosuggestProps, r
     warnOnce('Autosuggest', '`onLoadItems` must be provided for `recoveryText` to be displayed.');
   }
 
-  if (!enteredTextLabel) {
+  const enteredTextLabelI18nTestValue = i18n('enteredTextLabel', undefined, format => format({ value: '' }));
```
Comment (just-boris) [inline src/autosuggest/internal.tsx:89]: Technically this is a fix, but it is not stable, because it does not give a solid coupling between the actual label rendering and this warning. The logic may get out of sync and there will be regressions.

Thanks for the contribution, I will take it from there and do additional refactoring

**Review by just-boris — APPROVED** [review]

**Review by just-boris — APPROVED** [review]

File: src/autosuggest/internal.tsx (hunk 1 above)
Comment (tlindsay42) [reply src/autosuggest/internal.tsx:89]: For posterity: https://github.com/cloudscape-design/components/pull/1970
