### PR TITLE
chore: Fix sass deprecation warnings

### LINKED ISSUE #2571: [Bug]: Theming and nested rules
### Browser

_No response_

### Package version

3.0.687

### React version

18

### Description

When generating a theme for build-time theming I get errors for some (or every?) design tokens.  There are too many for me to view in my console but they all look like this:

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules/@cloudscape-design/components-themeable/lib/internal/scss/tutorial-panel/components/tutorial-list/motion.scss
13 │         animation: awsui-motion-fade-in tokens.$motion-duration-show-paced tokens.$motion-easing-show-paced;
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules/@cloudscape-design/components-themeable/lib/internal/scss/internal/styles/motion/animations.scss
9  │ ┌   @keyframes awsui-motion-fade-in {
10 │ │     from {
11 │ │       opacity: 0.2;
12 │ │     }
13 │ │ 
14 │ │     to {
15 │ │       opacity: 1;
16 │ │     }
17 │ │   }
   │ └─── nested rule
```

My `theme.ts`:
```
const path = require('path');
const {
  buildThemedComponents,
} = require('@cloudscape-design/components-themeable');

const theme = {
  tokens: {
    // Background colors
    colorBackgroundLayoutMain: {
      light: '#ffffff',
      dark: '#1b1b1b',
    },
  },
};

// module.exports = theme;

buildThemedComponents({
  theme,
  outputDir: path.join(__dirname, './styles/themed'),
});
```

Versions:
    "@cloudscape-design/component-toolkit": "^1.0.0-beta.58",
    "@cloudscape-design/components": "^3.0.687",
    "@cloudscape-design/components-themeable": "^3.0.729",
    "@cloudscape-design/design-tokens": "^3.0.43",
    "@cloudscape-design/global-styles": "^1.0.31",
    
    

### Reproduction

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by just-boris**
### Description

Resolves #2571

Related links, issue #, if available: n/a

### How has this been tested?

Screenshot tests in my pipeline

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: build-tools/tasks/styles.js [hunk 1]
```diff
@@ -78,6 +78,7 @@ function stylesTask(theme) {
       designTokensFileName: theme.designTokensOutput,
       descriptions,
       jsonSchema: true,
+      failOnDeprecations: true,
```
Comment (just-boris) [inline build-tools/tasks/styles.js:81]: Currently there are zero deprecation warnings. This line is to make sure it the build fails if anybody attempts using deprecated setup

File: src/app-layout/visual-refresh-toolbar/skeleton/styles.scss [hunk 2]
```diff
@@ -153,11 +153,11 @@
   margin-block-start: awsui.$space-scaled-s;
   margin-block-end: awsui.$space-layout-content-bottom;
   &-disable-paddings {
+    margin-block: 0;
     grid-column: 1 / -1;
     @include desktop-only {
       grid-column: 2 / span 3;
     }
-    margin-block: 0;
   }
```
Comment (just-boris) [inline src/app-layout/visual-refresh-toolbar/skeleton/styles.scss:161]: This snippet demonstrates the deprecated pattern very clear. Top level styles should always go first, before any nested rules.

File: src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/styles.scss [hunk 3]
```diff
@@ -63,13 +62,7 @@
   }
 }
 
-/*
-Warning! If these design tokens for width change it will adversely impact 
-the calculation used to determine the Split Panel maximum width in the 
-handleSplitPanelMaxWidth function in the context.
-*/
```
Comment (just-boris) [inline src/app-layout/visual-refresh-toolbar/toolbar/trigger-button/styles.scss:70]: This comment is copy-paste from VR app layout to the toolbar version, but it is not relevant anymore, because the implementation changed completely

File: src/calendar/styles.scss [hunk 4]
```diff
@@ -200,8 +201,6 @@
       }
     }
   }
-
-  @include styles.styles-reset;
```
Comment (just-boris) [inline src/calendar/styles.scss:204]: I do not know what to say here. Hiding the reset line here is a readability issue, great that the new deprecation forces us to fix this

**Review by dpitcock — DISMISSED** [review]
Thanks for the explanatory comments
