### PR TITLE
fix: dynamically added columns ignore minWidth

### LINKED ISSUE #4236: [Bug]: resizableColumns: dynamically added columns ignore minWidth, fall back to DEFAULT_COLUMN_WIDTH
### Browser

Chrome

### Package version

v3.0.0 (@amzn/awsui-components-console)

### React version

v19.2.3

### Description

When using `resizableColumns` on a `<Table>`, columns that are dynamically added to `columnDefinitions` (e.g. swapping visible columns based on a filter/toggle) do not respect their `minWidth`. They are instead assigned `DEFAULT_COLUMN_WIDTH` (120px).

The issue is in [`use-column-widths.tsx` L171](https://github.com/cloudscape-design/components/blob/9a1b7c5bf8e597df72f40a152f58bee9d09d2ac8/src/table/use-column-widths.tsx#L171):

```ts
newColumnWidths.set(column.id, column.width || DEFAULT_COLUMN_WIDTH);
```

This only checks `column.width` and ignores `column.minWidth`. A column defined with `{ minWidth: 250 }` but no explicit `width` will get 120px when dynamically added.

The initial render handles this correctly in `readWidths` ([L28-L41](https://github.com/cloudscape-design/components/blob/9a1b7c5bf8e597df72f40a152f58bee9d09d2ac8/src/table/use-column-widths.tsx#L28-L41)) by doing `Math.max(width, minWidth)`, but the dynamic column path does not.

### Expected behavior

Dynamically added columns should respect `minWidth`, consistent with the initial render behavior. The fix would be something like:

```ts
const minWidth = column.minWidth || column.width || DEFAULT_COLUMN_WIDTH;
newColumnWidths.set(column.id, Math.max(column.width || DEFAULT_COLUMN_WIDTH, minWidth));
```

### Workaround

Set an explicit `width` equal to `minWidth` on affected columns:

```ts
{
 id: 'myColumn',
 header: 'My Column',
 width: 250,    // workaround: must set width explicitly
 minWidth: 250,
 cell: (item) => item.value,
}
```

### Source code

[`use-column-widths.tsx` L171](https://github.com/cloudscape-design/components/blob/9a1b7c5bf8e597df72f40a152f58bee9d09d2ac8/src/table/use-column-widths.tsx#L171):

```ts
newColumnWidths.set(column.id, column.width || DEFAULT_COLUMN_WIDTH);
```

### Reproduction

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by SpyZzey**
### Description
Fixes #4236.
Currently, when adding columns to a table with minWidth > DEFAULT_COLUMN_WIDTH, they will still use DEFAULT_COLUMN_WIDTH, even though the minimum width is higher. This PR fixes this issue by checking if minWidth > DEFAULT_COLUMN_WIDTH and if so, setting the width to minWidth.

Related links, issue #, if available: n/a

### How has this been tested?
- Manually tested.
- Added unit tests.

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/table/use-column-widths.tsx [hunk 1]
```diff
@@ -168,7 +168,9 @@ export function ColumnWidthsProvider({ visibleColumns, resizableColumns, contain
         const column = visibleColumns[index];
         if (!columnWidths?.get(column.id) && lastVisible.indexOf(column.id) === -1) {
           updated = true;
-          newColumnWidths.set(column.id, (column.width as number) || DEFAULT_COLUMN_WIDTH);
+          const width = (column.width as number) || 0;
+          const minWidth = (column.minWidth as number) || width || DEFAULT_COLUMN_WIDTH;
+          newColumnWidths.set(column.id, Math.max(width || DEFAULT_COLUMN_WIDTH, minWidth));
```
Comment (NathanZlion) [inline src/table/use-column-widths.tsx]: nit: I think this can be simplified,
instead of doing `|| DEFAULT_COLUMN_WIDTH` 2 times here we can just default widths to that if not provided. And minWidth can be defaulted to width if not provided. then we just have to take max of the width and the minWidth.

```
const width = (column.width as number) || DEFAULT_COLUMN_WIDTH;
const minWidth = (column.minWidth as number) || width;
newColumnWidths.set(column.id, Math.max(width, minWidth));
```

same thing, but just makes it a bit simpler to read and understand.

Comment (SpyZzey) [reply src/table/use-column-widths.tsx]: Actually, my previous logic was flaws. The "|| 0" shouldn't have been there. Will update with your code, this simplification makes sense.
